task: climate_fever_binary_wo_evidence
dataset_path: climate_fever
output_type: multiple_choice
training_split: test
validation_split: test
test_split: test
doc_to_text: "Using the context as your primary source, is the following statement on climate correct or misinformation:\n{{claim}}\n"
doc_to_target: "{{claim_label}}" # will be 0 or 1
doc_to_choice: "{{['correct', 'misinformation']}}" # 0, 1
process_docs: !function utils.filter_binary # the dataset is rep'd as : 0 - true, 1 - false, N - other labels we don't want
