import re
import json
import pandas as pd

def evaluate_ai_response(correct_label, generated_label):
    """
    Evaluate the AI generated label based on the correct_label.
    
    Args:
    correct_label (str): The correct label for the response.
    generated_label (str): The label generated by the AI.
    
    Returns:
    str: 'correct', 'incorrect', or 'not valid' based on the evaluation.
    """

    def normalize_label(label):
        # Remove leading/trailing spaces and convert to uppercase
        label = label.strip().upper()
        # Split the label into parts (e.g., "B" and "NO")
        parts = re.split(r'\W+', label)
        return parts

    def contains_valid_answer(label):
        # Check if the label contains a valid answer format
        return bool(re.search(r'\b(A|B)\b|\b(CORRECT|MISINFORMATION)\b', label.upper()))

    # Normalize the generated label
    generated_label_normalized = ' '.join(normalize_label(generated_label)).upper()

    # If the generated label does not contain a valid answer format, return 'not valid'
    if not contains_valid_answer(generated_label):
        return 'invalid'

    # Normalize the correct label and check if it is in the generated label
    correct_label_parts = normalize_label(correct_label)
    if all(part in generated_label_normalized for part in correct_label_parts):
        return 'correct'
    else:
        return 'incorrect'

def process_csv(generated_answers, correct_labels):
    # Load CSV into DataFrame
    df = pd.read_csv(generated_answers)

    # Apply the evaluation function to each row using corresponding correct label
    df['eval'] = df.apply(lambda row: evaluate_ai_response(correct_labels[row.name], row['response']), axis=1)

    return df

def run(generated_answers, correct_answers, output_path):
    # Read the correct answers file and parse JSON lines
    correct_labels = []
    with open(correct_answers, 'r') as f:
        for line in f:
            json_obj = json.loads(line)
            correct_label = f"({json_obj['correct_choice_letter']}) {json_obj['correct_choice_text']}"
            correct_labels.append(correct_label)

    # Process the generated answers with the correct labels
    processed_df = process_csv(generated_answers, correct_labels)

    # Save the processed data to the output path
    processed_df.to_csv(output_path, index=False)

